from langchain_core.tools import tool

from database.db import get_connection


@tool
def get_customer_revenue(customer_name: str) -> str:
    """
    Calculate the total revenue generated by a specific customer.
    """

    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        SELECT
            c.name,
            COALESCE(SUM(o.total_amount), 0)
        FROM customers c
        LEFT JOIN orders o
            ON c.id = o.customer_id
        WHERE c.name LIKE ?
        GROUP BY c.id, c.name
    """, (f"%{customer_name.strip()}%",))

    results = cursor.fetchall()

    connection.close()

    if not results:
        return "Customer not found."

    revenue_data = []

    for customer in results:
        revenue_data.append({
            "customer": customer[0],
            "total_revenue": f"₹{customer[1]:,.2f}"
        })

    return str(revenue_data)