from langchain_core.tools import tool

from database.db import get_connection


@tool
def get_customer_revenue(
    customer_name: str,
    business_id: int
) -> str:
    """
    Calculate the total revenue generated by
    a specific customer within the
    authenticated business.
    """

    supabase = get_connection()

    # =========================
    # FIND CUSTOMER
    # =========================

    customer_response = (
        supabase
        .table("customers")
        .select("id, name")
        .eq("business_id", business_id)
        .ilike(
            "name",
            f"%{customer_name.strip()}%"
        )
        .execute()
    )

    customers = customer_response.data

    if not customers:
        return "Customer not found."

    revenue_data = []

    # =========================
    # FIND CUSTOMER ORDERS
    # =========================

    for customer in customers:

        order_response = (
            supabase
            .table("orders")
            .select("total_amount")
            .eq("customer_id", customer["id"])
            .eq("business_id", business_id)
            .execute()
        )

        orders = order_response.data

        total_revenue = sum(
            float(order["total_amount"])
            for order in orders
        )

        revenue_data.append({
            "customer": customer["name"],
            "total_revenue": f"₹{total_revenue:,.2f}"
        })

    return str(revenue_data)


if __name__ == "__main__":
    print(
        get_customer_revenue.invoke({
            "customer_name": "Rahul",
            "business_id": 1
        })
    )